import { defineField, defineType } from 'sanity'

export const post = defineType({
  name: 'post',
  title: 'Post / Article',
  type: 'document',
  groups: [
    { name: 'content',  title: 'Content',   default: true },
    { name: 'meta',     title: 'Metadata' },
    { name: 'seo',      title: 'SEO' },
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'content',
      validation: (Rule) => Rule.required().min(10).max(120),
    }),
    defineField({
      name: 'slug',
      title: 'Slug (URL)',
      type: 'slug',
      group: 'content',
      options: { source: 'title', maxLength: 96 },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'status',
      title: 'Publication status',
      type: 'string',
      group: 'meta',
      options: {
        list: [
          { value: 'draft',     title: '📝 Draft' },
          { value: 'review',    title: '🔍 In review' },
          { value: 'published', title: '✅ Published' },
        ],
        layout: 'radio',
      },
      initialValue: 'draft',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'contentType',
      title: 'Content type',
      type: 'string',
      group: 'meta',
      options: {
        list: [
          { value: 'article',      title: 'Article' },
          { value: 'field-note',   title: 'Field Note' },
          { value: 'news',         title: 'News' },
          { value: 'report',       title: 'Report' },
          { value: 'briefing',     title: 'Briefing' },
          { value: 'interview',    title: 'Interview' },
          { value: 'event-update', title: 'Event Update' },
        ],
      },
      initialValue: 'article',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'language',
      title: 'Language',
      type: 'string',
      group: 'meta',
      options: {
        list: [
          { value: 'en', title: '🇬🇧 English' },
          { value: 'bn', title: '🇧🇩 Bengali' },
        ],
        layout: 'radio',
      },
      initialValue: 'en',
    }),
    defineField({
      name: 'excerpt',
      title: 'Excerpt / Summary',
      type: 'text',
      group: 'content',
      rows: 3,
      description: 'Shown in article cards and SEO description fallback. Keep under 160 characters.',
      validation: (Rule) => Rule.max(300),
    }),
    defineField({
      name: 'coverImage',
      title: 'Cover image',
      type: 'image',
      group: 'content',
      options: { hotspot: true },
      fields: [
        defineField({ name: 'alt', type: 'string', title: 'Alt text', validation: (Rule) => Rule.required() }),
        defineField({ name: 'caption', type: 'string', title: 'Caption (optional)' }),
      ],
    }),
    defineField({
      name: 'author',
      title: 'Author',
      type: 'reference',
      group: 'meta',
      to: [{ type: 'author' }],
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'coAuthors',
      title: 'Co-authors',
      type: 'array',
      group: 'meta',
      of: [{ type: 'reference', to: [{ type: 'author' }] }],
    }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'reference',
      group: 'meta',
      to: [{ type: 'category' }],
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'tags',
      title: 'Tags',
      type: 'array',
      group: 'meta',
      of: [{ type: 'reference', to: [{ type: 'tag' }] }],
    }),
    defineField({
      name: 'publishedAt',
      title: 'Published at',
      type: 'datetime',
      group: 'meta',
      initialValue: () => new Date().toISOString(),
    }),
    defineField({
      name: 'updatedAt',
      title: 'Last updated at',
      type: 'datetime',
      group: 'meta',
    }),
    defineField({
      name: 'readingTime',
      title: 'Reading time (minutes)',
      type: 'number',
      group: 'meta',
      description: 'Leave blank to auto-calculate from body.',
    }),
    defineField({
      name: 'featured',
      title: 'Featured article',
      type: 'boolean',
      group: 'meta',
      initialValue: false,
      description: 'Show in homepage featured section.',
    }),
    defineField({
      name: 'editorPick',
      title: "Editor's pick",
      type: 'boolean',
      group: 'meta',
      initialValue: false,
    }),
    defineField({
      name: 'body',
      title: 'Body content',
      type: 'array',
      group: 'content',
      of: [
        { type: 'block' },
        {
          type: 'image',
          options: { hotspot: true },
          fields: [
            defineField({ name: 'alt', type: 'string', title: 'Alt text', validation: (Rule) => Rule.required() }),
            defineField({ name: 'caption', type: 'string', title: 'Caption' }),
          ],
        },
        {
          name: 'pullQuote',
          title: 'Pull quote',
          type: 'object',
          fields: [
            defineField({ name: 'quote', type: 'string', title: 'Quote text', validation: (Rule) => Rule.required() }),
            defineField({ name: 'attribution', type: 'string', title: 'Attribution (optional)' }),
          ],
          preview: { select: { title: 'quote' } },
        },
      ],
    }),
    defineField({
      name: 'seoTitle',
      title: 'SEO title',
      type: 'string',
      group: 'seo',
      description: 'Defaults to post title if blank. Keep under 60 characters.',
      validation: (Rule) => Rule.max(60),
    }),
    defineField({
      name: 'seoDescription',
      title: 'SEO description',
      type: 'text',
      group: 'seo',
      rows: 2,
      description: 'Defaults to excerpt if blank. Keep under 160 characters.',
      validation: (Rule) => Rule.max(160),
    }),
    defineField({
      name: 'ogImage',
      title: 'Open Graph image',
      type: 'image',
      group: 'seo',
      description: 'Social share image. Defaults to cover image. Ideal size: 1200×630px.',
      options: { hotspot: true },
    }),
  ],
  preview: {
    select: {
      title:    'title',
      author:   'author.name',
      media:    'coverImage',
      status:   'status',
      language: 'language',
    },
    prepare({ title, author, media, status, language }) {
      const statusIcon = status === 'published' ? '✅' : status === 'review' ? '🔍' : '📝'
      return {
        title: `${statusIcon} ${title}`,
        subtitle: `${author ?? 'No author'} · ${language?.toUpperCase()}`,
        media,
      }
    },
  },
  orderings: [
    { title: 'Published (newest)',  name: 'publishedAtDesc', by: [{ field: 'publishedAt', direction: 'desc' }] },
    { title: 'Published (oldest)',  name: 'publishedAtAsc',  by: [{ field: 'publishedAt', direction: 'asc' }] },
  ],
})
